[package]
name = "stocks"
version = "0.1.0"
authors = ["James <jamesleahy314@gmail.com>"]
edition = "2018"
description = "a cli tool to view stock data"

[dependencies]
rusqlite = "0.18.0"
requests = "0.0.30"
termion = "1.5.3"
clap = "2.33.0"
